Разделяй и властвуй
htmlacademy-schools/1903037-big-trip-1 pull request #10
Opened 2022-05-06 12:40 UTC by BotSmilee

---
:mortar_board: [Разделяй и властвуй](https://up.htmlacademy.ru/js2-urfu/1/user/1903037/tasks/7)

:boom: https://htmlacademy-schools.github.io/1903037-big-trip-1/10/

2022-05-08 19:10 UTC, yulllll commented on src/view/event-item-view.js
> +      // const {name, price} = offer;
у тебя здесь должна быть ошибка ведь цену и имя оффера мы берем из этого объекта, а не из tripEvent

2022-05-08 19:11 UTC, yulllll requested changes
посмотри причины почему проект не публикуется - их надо исправить

2022-05-13 06:50 UTC, yulllll commented
Проект не публикуется - исправь ошибки

2022-05-13 18:19 UTC, BotSmilee commented
> Проект не публикуется - исправь ошибки

Не понимаю, в чём ошибка

2022-05-14 13:04 UTC, merged