Module1 task2
htmlacademy-schools/1903037-big-trip-1 pull request #5
Opened 2022-03-03 06:39 UTC by BotSmilee

2022-03-03 09:03 UTC, what1s1ove commented on package.json
> +    "webpack": "^5.62.1",
обсуждали. это нужно к девзависимостям

2022-03-07 07:53 UTC, what1s1ove requested changes
все ещё есть конфликты

2022-03-07 18:18 UTC, BotSmilee commented
> r

Что нужно изменить?

2022-03-08 05:41 UTC, what1s1ove commented
> 

<img width="840" alt="image" src="https://user-images.githubusercontent.com/42296182/157173690-9d2542e2-0b27-49da-8ae3-ac733cbf50fa.png">

нужно решить кофликты. на прошлом занятии показывал как

2022-03-10 12:20 UTC, what1s1ove approved these changes

2022-03-10 12:20 UTC, merged